import type { GoalId, Supplement } from './types';

export const RULE_VERSION = 'suplan-demo-rules-0.1.0';

export const goalLabels: Record<GoalId, string> = {
  'daily-core': 'Daily Base',
  'active-day': 'Active Day',
  'plant-based': 'Plant-Based',
  glow: 'Glow Routine',
  'calm-pm': 'Calm PM',
  'focus-flow': 'Focus Flow',
};

export const supplements: Supplement[] = [
  {
    id: 'vitamin-d3',
    name: 'Vitamina D3',
    category: 'vitamina',
    summary: 'Un básico frecuente en rutinas de bienestar diario.',
    claim: 'La vitamina D contribuye al funcionamiento normal del sistema inmunitario y al mantenimiento de huesos normales.',
    tags: ['Daily Base', 'Active Day', 'Plant-Based'],
    defaultMoment: 'morning',
    vegan: false,
    allergens: [],
    maxDailyUnits: 1,
    caution: [],
  },
  {
    id: 'vegan-b12',
    name: 'Vitamina B12',
    category: 'vitamina',
    summary: 'Especialmente relevante en rutinas plant-based.',
    claim: 'La vitamina B12 contribuye al metabolismo energético normal y a disminuir el cansancio y la fatiga.',
    tags: ['Plant-Based', 'Daily Base', 'Focus Flow'],
    defaultMoment: 'morning',
    vegan: true,
    allergens: [],
    maxDailyUnits: 1,
    caution: [],
  },
  {
    id: 'magnesium',
    name: 'Magnesio',
    category: 'mineral',
    summary: 'Mineral popular para una rutina diaria simple.',
    claim: 'El magnesio contribuye a disminuir el cansancio y la fatiga y al funcionamiento normal de los músculos.',
    tags: ['Daily Base', 'Active Day', 'Calm PM'],
    defaultMoment: 'afternoon',
    vegan: true,
    allergens: [],
    maxDailyUnits: 2,
    caution: ['medication'],
  },
  {
    id: 'zinc',
    name: 'Zinc',
    category: 'mineral',
    summary: 'Usado en rutinas de piel, cabello, uñas y bienestar general.',
    claim: 'El zinc contribuye al mantenimiento normal de la piel, cabello y uñas.',
    tags: ['Glow Routine', 'Daily Base'],
    defaultMoment: 'morning',
    vegan: true,
    allergens: [],
    maxDailyUnits: 1,
    caution: [],
  },
  {
    id: 'omega-3-algae',
    name: 'Omega 3 de algas',
    category: 'omega',
    summary: 'Alternativa plant-based para rutinas que evitan aceite de pescado.',
    claim: 'DHA y EPA contribuyen al funcionamiento normal del corazón si se cumplen las condiciones de uso aplicables.',
    tags: ['Plant-Based', 'Active Day'],
    defaultMoment: 'morning',
    vegan: true,
    allergens: [],
    maxDailyUnits: 2,
    caution: ['medication'],
  },
  {
    id: 'biotin',
    name: 'Biotina',
    category: 'vitamina',
    summary: 'Frecuente en rutinas de cuidado personal.',
    claim: 'La biotina contribuye al mantenimiento normal del cabello y la piel.',
    tags: ['Glow Routine'],
    defaultMoment: 'morning',
    vegan: true,
    allergens: [],
    maxDailyUnits: 1,
    caution: [],
  },
  {
    id: 'l-theanine',
    name: 'L-teanina',
    category: 'aminoacido',
    summary: 'Ingrediente de uso frecuente en rutinas de tarde, pendiente de validación regulatoria por mercado.',
    claim: 'Ingrediente informativo para demo. Claims finales requieren revisión regulatoria antes de venta.',
    tags: ['Calm PM', 'Focus Flow'],
    defaultMoment: 'afternoon',
    vegan: true,
    allergens: [],
    maxDailyUnits: 1,
    caution: ['medical-condition', 'medication'],
  },
  {
    id: 'vitamin-c',
    name: 'Vitamina C',
    category: 'vitamina',
    summary: 'Vitamina sencilla para rutinas de bienestar general.',
    claim: 'La vitamina C contribuye a la formación normal de colágeno para el funcionamiento normal de la piel.',
    tags: ['Daily Base', 'Glow Routine'],
    defaultMoment: 'morning',
    vegan: true,
    allergens: [],
    maxDailyUnits: 1,
    caution: [],
  },
];
